FROM alpine:latest

ADD ./dist/ui/dist /app/gateway/ui
ADD ./dist/apiserver /usr/local/bin/

RUN mkdir -p /var/apiserver/
RUN mkdir -p /var/lib/apiserver/

# Alpine Linux doesn't use pam, which means that there is no /etc/nsswitch.conf,
# but Golang relies on /etc/nsswitch.conf to check the order of DNS resolving
# (see https://github.com/golang/go/commit/9dee7771f561cf6aee081c0af6658cc81fac3918)
# To fix this we just create /etc/nsswitch.conf and add the following line:
RUN echo 'hosts: files mdns4_minimal [NOTFOUND=return] dns mdns4' >> /etc/nsswitch.conf

EXPOSE 9092 9093

# Define default command.
ENTRYPOINT ["/usr/local/bin/apiserver"]